import { test, expect } from '@playwright/test';
import { resolve } from 'node:path';
import { readFile } from 'node:fs/promises';
test('real browser → API → Orca → validated G-code download', async ({ page, request }) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  const aboutResponse = await request.get('/api/about');
  expect(aboutResponse.ok()).toBeTruthy();
  const about = await aboutResponse.json();
  expect(about.slicerAvailable, 'This integration test requires a real installed Orca runtime').toBe(true);
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Orca Web', exact: true })).toBeVisible();
  await page.getByTestId('model-upload').setInputFiles(resolve('fixtures/cube-20mm.stl'));
  await expect(page.getByText('cube-20mm.stl', { exact: true }).first()).toBeVisible();
  await expect(page.getByTestId('model-preview')).toHaveAttribute('data-loaded', 'true');
  // A flip must restore bed contact even when the user previously disabled placement.
  await page.getByRole('checkbox', { name: 'Ensure on bed' }).uncheck();
  await page.getByRole('checkbox', { name: 'Auto orient' }).check();
  await page.getByRole('button', { name: 'Flip X 180 degrees' }).click();
  await expect(page.getByRole('checkbox', { name: 'Ensure on bed' })).toBeChecked();
  await expect(page.getByRole('checkbox', { name: 'Auto orient' })).not.toBeChecked();
  await expect.poll(async () => Number(await page.getByTestId('model-preview').getAttribute('data-min-z'))).toBeCloseTo(0, 6);
  await page.getByRole('button', { name: 'Turn Y 90 degrees' }).click();
  await expect.poll(async () => Number(await page.getByTestId('model-preview').getAttribute('data-min-z'))).toBeCloseTo(0, 6);
  await page.getByRole('button', { name: 'Place on face', exact: true }).click();
  const canvas = page.locator('canvas');
  const canvasBounds = (await canvas.boundingBox())!;
  await canvas.click({ position: { x: canvasBounds.width * 0.5, y: canvasBounds.height * 0.52 } });
  await expect(page.getByRole('button', { name: 'Place on face', exact: true })).toHaveAttribute('aria-pressed', 'false');
  await expect.poll(async () => Number(await page.getByTestId('model-preview').getAttribute('data-min-z'))).toBeCloseTo(0, 6);
  // Infill and supports work independently of the advanced custom-settings toggle.
  await expect(page.getByRole('tab', { name: 'Basic', exact: true })).toHaveAttribute('aria-selected', 'true');
  await page.getByRole('spinbutton', { name: 'Infill percentage' }).fill('25');
  await page.getByRole('combobox', { name: 'Infill pattern', exact: true }).selectOption('gyroid');
  await page.getByRole('combobox', { name: 'Supports', exact: true }).selectOption('true');
  await page.getByRole('combobox', { name: 'Support type', exact: true }).selectOption('tree(auto)');
  await page.getByRole('combobox', { name: 'Support placement', exact: true }).selectOption('true');
  const slice = page.getByRole('button', { name: 'Slice', exact: true });
  await expect(slice).toBeEnabled();
  await slice.click();
  const downloadLink = page.getByRole('link', { name: /Download G-code/i }).first();
  await expect(downloadLink).toBeVisible({ timeout: 150000 });
  const response = await request.get((await downloadLink.getAttribute('href'))!);
  expect(response.ok()).toBeTruthy();
  const code = await response.text();
  expect(code).toMatch(/generated by OrcaSlicer/i);
  expect(code).toMatch(/Ender-3 V3 KE/);
  expect(code).toMatch(/G[01]\s/);
  expect(code).toMatch(/; sparse_infill_density = 25%/);
  expect(code).toMatch(/; sparse_infill_pattern = gyroid/);
  expect(code).toMatch(/; enable_support = 1\s/);
  expect(code).toMatch(/; support_type = tree\(auto\)/);
  expect(code).toMatch(/; support_on_build_plate_only = 1\s/);
  expect(code.startsWith('; png begin 96*96 ')).toBe(true);
  const blocks = [...code.matchAll(/^; (png|thumbnail) begin (\d+)[*x](\d+) (\d+)[^\n]*\n((?:; [A-Za-z0-9+/=]+\n)+); \1 end/gm)];
  expect(blocks).toHaveLength(4);
  const decoded = await page.evaluate(async (payloads) => Promise.all(payloads.map(async payload => {
    const image = new Image(); image.src = 'data:image/png;base64,' + payload;
    await image.decode();
    return [image.naturalWidth, image.naturalHeight];
  })), blocks.map(block => block[5].split('\n').filter(Boolean).map(line => line.slice(2)).join('')));
  expect(decoded).toEqual([[96, 96], [300, 300], [96, 96], [300, 300]]);
  const pendingDownload = page.waitForEvent('download');
  await downloadLink.click();
  const download = await pendingDownload;
  expect(download.suggestedFilename()).toBe('cube-20mm.gcode');
  expect(await download.failure()).toBeNull();
  expect(errors).toEqual([]);
});

test('phone shows job history and downloads', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await page.getByRole('button', { name: /Jobs/i, exact: true }).click();
  await expect(page.getByText('cube-20mm.stl', { exact: true }).first()).toBeVisible();
  await expect(page.getByRole('link', { name: /Download G-code/i }).first()).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)).toBe(false);
});

for (const viewport of [{ width: 1440, height: 700 }, { width: 768, height: 800 }, { width: 390, height: 844 }]) {
  test(`full settings and long model names remain readable at ${viewport.width}px`, async ({ page }) => {
    await page.setViewportSize(viewport);
    await page.route('**/api/about', route => route.fulfill({ json: { slicerAvailable: true, orcaVersion: '2.4.2', supportedFormats: ['stl'], maxUploadMb: 250 } }));
    const machineId = 'printer', processId = 'process', filamentId = 'filament';
    await page.route('**/api/presets', route => route.fulfill({ json: {
      defaults: { machineId, processId, filamentId },
      machines: [{ id: machineId, name: 'Creality Ender-3 V3 KE 0.4 nozzle', compatibleMachineIds: [], nozzleDiameter: 0.4, buildVolume: { width: 220, depth: 220, height: 245 } }],
      processes: [{ id: processId, name: '0.20mm Standard @Creality Ender3V3KE', compatibleMachineIds: [machineId] }],
      filaments: [{ id: filamentId, name: 'Creality Generic PLA @Ender-3V3-all', compatibleMachineIds: [machineId] }],
    } }));
    await page.goto('/');
    const name = 'a-long-model-name-with-several-words-and-dimensions-220x220-final-version.stl';
    await page.getByTestId('model-upload').setInputFiles({ name, mimeType: 'model/stl', buffer: await readFile(resolve('fixtures/cube-20mm.stl')) });
    await expect(page.getByTestId('model-preview')).toHaveAttribute('data-loaded', 'true');
    for (const label of ['Infill pattern', 'Support placement']) {
      const field = page.getByRole('combobox', { name: label, exact: true });
      await field.scrollIntoViewIfNeeded();
      await expect(field).toBeInViewport();
      await field.click({ trial: true });
    }
    await page.getByRole('tab', { name: 'Advanced', exact: true }).click();
    await page.getByRole('checkbox', { name: 'Custom print settings' }).check();
    for (const label of ['Layer height', 'Retraction length', 'Brim']) {
      const field = page.getByLabel(label, { exact: true });
      await field.scrollIntoViewIfNeeded();
      await expect(field).toBeInViewport();
    }
    const layout = await page.evaluate(() => {
      const settings = document.querySelector('.settings-panel')!;
      const labels = [...document.querySelectorAll('.model-file-info strong, .slice-bar strong, .selected-preset')];
      return {
        overflow: document.documentElement.scrollWidth > window.innerWidth,
        clippedSettings: settings.scrollHeight > settings.clientHeight + 1,
        clippedLabels: labels.some(element => element.scrollWidth > element.clientWidth + 1),
        shortenedLabels: labels.some(element => getComputedStyle(element).textOverflow === 'ellipsis'),
      };
    });
    await page.screenshot({ path: test.info().outputPath('layout.png'), fullPage: true });
    expect(layout).toEqual({ overflow: false, clippedSettings: false, clippedLabels: false, shortenedLabels: false });
    await page.getByRole('tab', { name: 'Basic', exact: true }).click();
    await page.getByRole('combobox', { name: 'Supports', exact: true }).selectOption('false');
    await expect(page.getByRole('combobox', { name: 'Support type', exact: true })).toBeDisabled();
    await expect(page.getByRole('combobox', { name: 'Support placement', exact: true })).toBeDisabled();
  });
}
