import { describe,it,expect } from 'vitest';
import { parseGcodeMetadata } from '../src/gcode/metadata.js';
describe('G-code metadata',()=>{
 it('parses verified Orca header and config fields',()=>{
  const m=parseGcodeMetadata('; generated by OrcaSlicer 2.4.2\nG1 X110 Y110 E1\n; printer_settings_id = Creality Ender-3 V3 KE 0.4 nozzle\n; estimated printing time (normal mode) = 16m 51s\n; filament used [mm] = 1234.56\n; filament used [g] = 3.7\n');
  expect(m).toEqual({printerName:'Creality Ender-3 V3 KE 0.4 nozzle',estimatedPrintTime:'16m 51s',filamentLengthMm:1234.56,filamentWeightGrams:3.7,generatedByOrca:true,hasMotion:true});
 });
 it('does not report invented statistics on incomplete output',()=>{const m=parseGcodeMetadata('; filament used [g] = no\n');expect(m.filamentWeightGrams).toBeUndefined();expect(m.generatedByOrca).toBe(false);expect(m.hasMotion).toBe(false);});
});
