import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {afterEach,beforeEach,describe,it,expect} from 'vitest';
import {sliceOptionsSchema,type Job,type JobStatus} from '@orca-web/shared';
import {JobStore} from '../src/storage/jobs.js';
import {SliceQueue} from '../src/jobs/queue.js';
import {jobPaths} from '../src/storage/paths.js';
import {config,registry,machineName} from './fixtures.js';
let dir:string;let store:JobStore;let queue:SliceQueue|undefined;
beforeEach(async()=>{dir=await fs.mkdtemp(path.join(os.tmpdir(),'orca-queue-'));store=new JobStore(dir);});
afterEach(async()=>{await queue?.close();store.close();await fs.rm(dir,{recursive:true,force:true});queue=undefined;});
async function addJob() {
 const id=randomUUID(),p=jobPaths(dir,id);await Promise.all([fs.mkdir(p.input,{recursive:true}),fs.mkdir(p.work,{recursive:true}),fs.mkdir(p.output,{recursive:true})]);await fs.writeFile(p.inputFile,'solid fixture\nendsolid fixture');
 const now=new Date().toISOString();const job:Job={id,status:'queued',filename:'fixture.stl',options:sliceOptionsSchema.parse(registry().catalog.defaults),presets:{machine:machineName,process:'Process',filament:'PLA'},createdAt:now,updatedAt:now};store.create(job);return job;
}
async function binary(source:string) {const name=path.join(dir,'fake-orca.cjs');await fs.writeFile(name,`#!/usr/bin/env node\n${source}`,{mode:0o700});return name;}
async function waitStatus(id:string,status:JobStatus) {const deadline=Date.now()+3000;while(Date.now()<deadline){if(store.get(id)!.status===status)return;await new Promise(r=>setTimeout(r,10));}throw new Error(`Job status stayed ${store.get(id)?.status}, expected ${status}`);}
describe('persistent one-process slice queue',()=>{
 it('resumes queued records after startup and preserves concurrency bound',async()=>{
  const executable=await binary(`const fs=require('node:fs'),path=require('node:path');const out=process.argv[process.argv.indexOf('--outputdir')+1];setTimeout(()=>{fs.writeFileSync(path.join(out,'plate_1.gcode'),'; generated by OrcaSlicer 2.4.2\\n; total layer number: 1\\n;TYPE:Outer wall\\nG1 X110 Y110 E1\\n; printer_settings_id = ${machineName}\\n');},150);`);
  const first=await addJob(),second=await addJob();queue=new SliceQueue(store,config(dir,executable),registry(),'2.4.2');
  await waitStatus(first.id,'running');expect(store.get(second.id)!.status).toBe('queued');
  await waitStatus(first.id,'succeeded');await waitStatus(second.id,'succeeded');expect(store.get(second.id)!.result!.files[0]!.size).toBeGreaterThan(0);expect(store.get(second.id)!.result!.files[0]!.name).toBe('fixture.gcode');expect(await fs.readdir(jobPaths(dir,second.id).output)).toEqual(['fixture.gcode']);
 });
 it('cancels queued and running jobs without later reporting success',async()=>{
  const executable=await binary('setInterval(()=>{},100);');const first=await addJob(),second=await addJob();queue=new SliceQueue(store,config(dir,executable),registry(),'2.4.2');
  await waitStatus(first.id,'running');expect(queue.cancel(second.id).status).toBe('canceled');expect(queue.cancel(first.id).status).toBe('canceled');
  await queue.close();expect(store.get(first.id)!.status).toBe('canceled');expect(store.get(second.id)!.status).toBe('canceled');
 });
 it('marks timed-out work failed and advances the queue',async()=>{
  const executable=await binary('setInterval(()=>{},100);');const first=await addJob();const cfg=config(dir,executable);cfg.slicerTimeoutSeconds=0.15;queue=new SliceQueue(store,cfg,registry(),'2.4.2');
  await waitStatus(first.id,'failed');expect(store.get(first.id)!.error).toContain('timed out');
 });
});
