import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { crc32, inflateSync } from 'node:zlib';
import { embedGcodeThumbnails, renderGcodeThumbnails } from '../src/gcode/thumbnails.js';

let directory: string;
beforeEach(async () => { directory = await mkdtemp(join(tmpdir(), 'orca-thumbnail-')); });
afterEach(async () => { await rm(directory, { recursive: true, force: true }); });
const sample = '; generated by OrcaSlicer 2.4.2\n; total layer number: 3\nM83\nG0 X10 Y10 Z0.2\n;TYPE:Outer wall\n;WIDTH:0.42\nG1 X30 E1\nG1 Y30 E1\nG1 X10 E1\nG1 Y10 E1\nG0 Z2\nG1 X30 E1\nG1 Y30 E1\nG1 X10 E1\nG1 Y10 E1\n;TYPE:Custom\nG1 X-100 Y-100 E50\n';

function decode(png: Buffer) {
  expect(png.subarray(0, 8)).toEqual(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]));
  const chunks: Buffer[] = [];
  let width = 0, height = 0, finished = false;
  for (let offset = 8; offset < png.length;) {
    const length = png.readUInt32BE(offset), type = png.toString('ascii', offset + 4, offset + 8);
    expect(png.readUInt32BE(offset + length + 8)).toBe(crc32(png.subarray(offset + 4, offset + length + 8)));
    const data = png.subarray(offset + 8, offset + 8 + length);
    if (type === 'IHDR') { width = data.readUInt32BE(0); height = data.readUInt32BE(4); expect([...data.subarray(8)]).toEqual([8, 6, 0, 0, 0]); }
    if (type === 'IDAT') chunks.push(data);
    if (type === 'IEND') finished = true;
    offset += length + 12;
  }
  expect(finished).toBe(true);
  const raw = inflateSync(Buffer.concat(chunks));
  expect(raw.length).toBe((width * 4 + 1) * height);
  const alpha: number[] = [];
  for (let y = 0; y < height; y++) {
    expect(raw[y * (width * 4 + 1)]).toBe(0);
    for (let x = 0; x < width; x++) alpha.push(raw[y * (width * 4 + 1) + 1 + x * 4 + 3]);
  }
  return { width, height, alpha };
}

describe('printer G-code previews', () => {
  it('renders valid, nonempty PNGs at both required sizes', async () => {
    const file = join(directory, 'part.gcode'); await writeFile(file, sample);
    const { images, layerCount } = await renderGcodeThumbnails(file);
    expect(layerCount).toBe(3); expect(images.map(image => image.size)).toEqual([96, 300]);
    for (const image of images) {
      const { width, height, alpha } = decode(image.png);
      expect([width, height]).toEqual([image.size, image.size]);
      expect(alpha.filter(value => value > 0).length).toBeGreaterThan(100);
      expect(alpha[0]).toBe(0); expect(alpha.at(-1)).toBe(0);
      const visibleRows = alpha.flatMap((value, index) => value ? [Math.floor(index / width)] : []);
      expect(image.firstRow).toBe(Math.min(...visibleRows)); expect(image.lastRow).toBe(Math.max(...visibleRows));
    }
  });
  it('embeds native Creality and standard blocks with accurate lengths and preserves every original byte', async () => {
    const file = join(directory, 'part.gcode'); await writeFile(file, sample);
    await embedGcodeThumbnails(file);
    const output = await readFile(file, 'utf8');
    expect(output.startsWith('; png begin 96*96 ')).toBe(true); expect(output.endsWith(sample)).toBe(true);
    const blocks = [...output.matchAll(/^; (png|thumbnail) begin (\d+)[*x](\d+) (\d+)([^\n]*)\n((?:; [A-Za-z0-9+/=]+\n)+); \1 end/gm)];
    expect(blocks).toHaveLength(4);
    for (const block of blocks) {
      const encoded = block[6].split('\n').filter(Boolean).map(line => line.slice(2)).join('');
      expect(encoded.length).toBe(Number(block[4]));
      const { width, height } = decode(Buffer.from(encoded, 'base64'));
      expect([width, height]).toEqual([Number(block[2]), Number(block[3])]);
      if (block[1] === 'png') expect(block[5].trim().split(' ').at(-1)).toBe('3');
    }
    const once = await readFile(file);
    await embedGcodeThumbnails(file);
    expect(await readFile(file)).toEqual(once);
  });
  it('ignores travel, purge, retractions and brim when framing the model', async () => {
    const first = join(directory, 'first.gcode'), second = join(directory, 'second.gcode');
    await writeFile(first, sample);
    await writeFile(second, ';TYPE:Custom\nM83\nG1 X999 Y999 Z999 E10\n' + sample + ';TYPE:Brim\nG1 X999 Y999 E10\nG1 X-999 E-1\nG0 Y-999\n');
    expect((await renderGcodeThumbnails(second)).images.map(image => image.png)).toEqual((await renderGcodeThumbnails(first)).images.map(image => image.png));
  });
  it('handles absolute extrusion, G92 resets and relative coordinates equivalently', async () => {
    const absolute = join(directory, 'absolute.gcode'), relative = join(directory, 'relative.gcode');
    await writeFile(absolute, ';TYPE:Outer wall\nM82\nG0 X10 Y10 Z1\nG1 X30 E1\nG1 Y30 E2\nG92 E0\nG1 X10 E1\nG1 Y10 E2\n');
    await writeFile(relative, ';TYPE:Outer wall\nM83\nG0 X10 Y10 Z1\nG91\nG1 X20 E1\nG1 Y20 E1\nG1 X-20 E1\nG1 Y-20 E1\n');
    expect((await renderGcodeThumbnails(absolute)).images.map(image => image.png)).toEqual((await renderGcodeThumbnails(relative)).images.map(image => image.png));
  });
  it('renders fitted arcs, including full circles', async () => {
    const file = join(directory, 'circle.gcode');
    await writeFile(file, ';TYPE:Outer wall\nM83\nG0 X20 Y10 Z1\nG2 X20 Y10 I-10 J0 E20\n');
    const { images } = await renderGcodeThumbnails(file);
    for (const image of images) expect(decode(image.png).alpha.filter(value => value > 0).length).toBeGreaterThan(100);
  });
  it('refuses a blank preview rather than silently embedding an empty image', async () => {
    const file = join(directory, 'empty.gcode'); await writeFile(file, ';TYPE:Custom\nG1 X10 E1\n');
    await expect(embedGcodeThumbnails(file)).rejects.toThrow('no printable extrusion');
    expect(await readFile(file, 'utf8')).toBe(';TYPE:Custom\nG1 X10 E1\n');
  });
  it('leaves the original file intact when canceled', async () => {
    const file = join(directory, 'canceled.gcode'); await writeFile(file, sample);
    const controller = new AbortController(); controller.abort();
    await expect(embedGcodeThumbnails(file, controller.signal)).rejects.toThrow();
    expect(await readFile(file, 'utf8')).toBe(sample);
  });
});
