import fs from 'node:fs/promises';
export interface GcodeMetadata { printerName?: string; estimatedPrintTime?: string; filamentLengthMm?: number; filamentWeightGrams?: number; generatedByOrca: boolean; hasMotion: boolean }
export function parseGcodeMetadata(text: string): GcodeMetadata {
  const field = (key: string): string | undefined => text.match(new RegExp(`^;\\s*${key}\\s*=\\s*(.+)$`, 'mi'))?.[1]?.trim();
  const numeric = (value: string | undefined) => { if (!value) return undefined; const n = Number.parseFloat(value); return Number.isFinite(n) && n >= 0 ? n : undefined; };
  return { printerName: field('printer_settings_id')?.replace(/^"|"$/g, ''),
    estimatedPrintTime: field('estimated printing time \\(normal mode\\)') ?? field('estimated printing time'),
    filamentLengthMm: numeric(field('filament used \\[mm\\]')), filamentWeightGrams: numeric(field('filament used \\[g\\]')),
    generatedByOrca: /generated by OrcaSlicer/i.test(text), hasMotion: /^G[01]\s+.*(?:X|Y|Z|E)[-\d.]/m.test(text) };
}
export async function readGcodeMetadata(filename: string): Promise<GcodeMetadata> {
  const handle = await fs.open(filename, 'r');
  try {
    const { size } = await handle.stat(); const sampleSize = Math.min(size, 1024 * 1024);
    const head = Buffer.alloc(sampleSize); const tail = Buffer.alloc(sampleSize);
    await handle.read(head, 0, sampleSize, 0); await handle.read(tail, 0, sampleSize, Math.max(0, size - sampleSize));
    return parseGcodeMetadata(head.toString('utf8') + '\n' + tail.toString('utf8'));
  } finally { await handle.close(); }
}
